services:
  e-test:
    image: e-test-env
    build:
      context: .
      dockerfile: Dockerfile

    container_name: e-test

    env_file:
      - .env

    ports:
      - "20268:8888"

    volumes:
      - ./AutonomicTester/experiment_results:/app/AutonomicTester/experiment_results
      - opt:/opt

    working_dir: /app

    tty: true
    stdin_open: true

    restart: "no"
volumes:
  opt:
