version: "3.9"

services:
  e-test:
    image: e-test-env
    build:
      context: .
      dockerfile: Dockerfile

    container_name: e-test

    env_file:
      - .env

    ports:
      - "20268:8888"

    volumes:
      - .:/app

    working_dir: /app

    tty: true
    stdin_open: true

    restart: "no"
